Practica20240402.UI.AppWebMVC/Models/ErrorViewModel.cs
namespace Practica20240402.UI.AppWebMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Practica20240402.UI.AppWebMVC/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;
using Practica20240402.EntidadesDeNegocio;
using Practica20240402.LogicaDeNegocio;
namespace Practica20240402.UI.AppWebMVC.Controllers
{
    public class ClienteController : Controller
    {
        readonly ClienteBL _clienteBL;
        public ClienteController(ClienteBL clienteBL) {
            _clienteBL=clienteBL;
        }
        // GET: ClienteController
        public async  Task<ActionResult> Index(Cliente cliente)
        {
            var clientes = await _clienteBL.Buscar(cliente);
            return View(clientes);
        }

        // GET: ClienteController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var cliente = await _clienteBL.ObtenerPorId(new Cliente {Id=id });
            return View(cliente);
        }

        // GET: ClienteController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ClienteController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Cliente cliente)
        {
            try
            {
                await _clienteBL.Crear(cliente);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ClienteController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var cliente = await _clienteBL.ObtenerPorId(new Cliente { Id = id });
            return View(cliente);
        }

        // POST: ClienteController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async  Task<ActionResult> Edit(Cliente cliente)
        {
            try
            {
                await _clienteBL.Modificar(cliente);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ClienteController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var cliente = await _clienteBL.ObtenerPorId(new Cliente { Id = id });
            return View(cliente);
        }

        // POST: ClienteController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, Cliente cliente)
        {
            try
            {
                await _clienteBL.Eliminar(cliente);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        public ActionResult GraficoPorEdades()
        {           
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> GetInfoGraficoPorEdades()
        {
            var clientes = await _clienteBL.ObtenerTodos();
            var yearActual = DateTime.Now.Year;
            //2024-18 = 2012
            // 2024-30 = 1994
            var clienteEntre18y30 = clientes.Where(s => s.FechaNacimiento.Year> (yearActual-30) && s.FechaNacimiento.Year <= (yearActual - 18));
            var clienteEntre31y50 = clientes.Where(s => s.FechaNacimiento.Year > (yearActual - 50) && s.FechaNacimiento.Year <= (yearActual - 30));
            var clientemayoresa50 = clientes.Where(s => s.FechaNacimiento.Year > (yearActual - 200) && s.FechaNacimiento.Year <= (yearActual - 50));
            var objs = new List<object>();
            objs.Add(new
            {
                grupo = "Entre 18 y 30 años",
                cantidad = clienteEntre18y30.Count(),
            });
            objs.Add(new
            {
                grupo = "Entre 30 y 50 años",
                cantidad = clienteEntre31y50.Count(),
            });
            objs.Add(new
            {
                grupo = "Mayores a 50 años",
                cantidad = clientemayoresa50.Count(),
            });
            return Json(objs);
        }
    }
}

Practica20240402.UI.AppWebMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Practica20240402.UI.AppWebMVC.Models;
using System.Diagnostics;

namespace Practica20240402.UI.AppWebMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Practica20240402.UI.AppWebMVC/Views/Cliente/Create.cshtml
@model Practica20240402.EntidadesDeNegocio.Cliente

@{
    ViewData["Title"] = "Create";
}

<h1>Crear</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>           
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaNacimiento" class="control-label"></label>
                <input asp-for="FechaNacimiento" class="form-control" />
                <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Cancelar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Practica20240402.UI.AppWebMVC/Views/Cliente/Delete.cshtml
@model Practica20240402.EntidadesDeNegocio.Cliente

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">       
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Cancelar</a>
    </form>
</div>

Practica20240402.UI.AppWebMVC/Views/Cliente/Details.cshtml
@model Practica20240402.EntidadesDeNegocio.Cliente

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">      
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Ir a editar", "Edit", new {  id = Model.Id  }) |
    <a asp-action="Index">Cancelar</a>
</div>

Practica20240402.UI.AppWebMVC/Views/Cliente/Edit.cshtml
@model Practica20240402.EntidadesDeNegocio.Cliente

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Id" type="hidden" class="form-control" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaNacimiento" class="control-label"></label>
                <input asp-for="FechaNacimiento" class="form-control" />
                <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Modificar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Cancelar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Practica20240402.UI.AppWebMVC/Views/Cliente/GraficoPorEdades.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<script src="https://www.gstatic.com/charts/loader.js"></script>
<div id="myChartPastel" style="width:100%; max-width:800px; height:700px;">
</div>
<div id="myChartBarra" style="width:100%; max-width:800px; height:700px;">
</div>
@section Scripts {
    <script>

        google.charts.load('current', { 'packages': ['corechart'] });
        var datosGrafico = {};

        function drawChartPastel() {

            // Set Data
            const data = google.visualization.arrayToDataTable(datosGrafico);

            // Set Options
            const options = {
                title: 'Cliente por edades grafico de pastel',
                is3D: true
            };

            // Draw
            const chart = new google.visualization.PieChart(document.getElementById('myChartPastel'));
            chart.draw(data, options);

        }
        function drawChartBarra() {

            // Set Data
            const data = google.visualization.arrayToDataTable(datosGrafico);

            // Set Options            

            // Draw
            const options = {
                title: 'Cliente por edades grafico de barra'
            };

            // Draw
            const chart = new google.visualization.BarChart(document.getElementById('myChartBarra'));
            chart.draw(data, options);

        }
        function iniciar() {
            $.ajax({
                url: '@Url.Action("GetInfoGraficoPorEdades", "Cliente")',
                method: "POST",
                success: function (response) {                   
                    datosGrafico = [
                        ['Contry', 'Mhl']                                          
                    ];
                    for (var i = 0; i < response.length; i++) {
                        const item = response[i];                     
                        datosGrafico.push([item.grupo, item.cantidad]);                       
                    }
                    google.charts.setOnLoadCallback(drawChartPastel);
                    google.charts.setOnLoadCallback(drawChartBarra);
                   
                },
                error: function (error) {
                    console.log("Error creating user:", error);
                }
            });

        }
        iniciar();
    </script>
}

Practica20240402.UI.AppWebMVC/Views/Cliente/Index.cshtml
@model IEnumerable<Practica20240402.EntidadesDeNegocio.Cliente>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<form asp-action="Index">
    <div class="row">
        <div class="form-group col-3">
            <label  class="control-label">Nombre</label>
            <input type="text" name="nombre" class="form-control" />           
        </div>
        <div class="form-group col-3">
            <label class="control-label">Apellido</label>
            <input type="text" name="apellido" class="form-control" />
        </div>
    </div>
    <div class="row">
        <div class="form-group col-12">
            <input type="submit" value="Buscar" class="btn btn-primary" />
            <a asp-action="Create" class="btn btn-primary">Crear</a>
            <a asp-action="GraficoPorEdades" class="btn btn-primary">Graficos</a>
        </div>
    </div>
</form>
<p>
  
</p>
<table class="table">
    <thead>
        <tr>          
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaNacimiento)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>           
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaNacimiento)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new {  id=item.Id  }) |
                @Html.ActionLink("Detalle", "Details", new { id=item.Id  }) |
                @Html.ActionLink("Eliminar", "Delete", new {  id=item.Id  })
            </td>
        </tr>
}
    </tbody>
</table>

Practica20240402.UI.AppWebMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Practica20240402.UI.AppWebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Practica20240402.UI.AppWebMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Practica20240402.UI.AppWebMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Practica20240402.UI.AppWebMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Practica20240402.UI.AppWebMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>